version: "2"

plugins:
  brakeman:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        - ruby
    exclude_patterns:
      - spec/
  reek:
    enabled: true
    directories:
      "app/controllers":
        IrresponsibleModule:
          enabled: false
        NestedIterators:
          max_allowed_nesting: 2
        UnusedPrivateMethod:
          enabled: false
        InstanceVariableAssumption:
          enabled: false
      "app/helpers":
        IrresponsibleModule:
          enabled: false
        UtilityFunction:
          enabled: false
      "app/mailers":
        InstanceVariableAssumption:
          enabled: false
      "app/models":
        InstanceVariableAssumption:
          enabled: false
  rubocop:
    enabled: true
    channel: rubocop-0-83

exclude_patterns:
  - "app/**/application*"
  - "bin/bundle"
  - "config/"
  - "db/"
  - "dist/"
  - "**/node_modules/"
  - "script/"
  - "**/vendor/"
  - "tmp/"
