require:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - app/**/application*
    - bin/bundle
    - db/schema.rb
    - db/migrate/*.rb
    - node_modules/**/*

Metrics/BlockLength:
  Enabled: true
  Exclude: 
    - spec/**/*